# Generated by Django 3.1.2 on 2020-10-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth_female',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=15)),
                ('size', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cloth_male',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=15)),
                ('size', models.CharField(max_length=15)),
            ],
        ),
    ]
