# Generated by Django 3.1.2 on 2020-10-20 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloth_female',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cloth_male',
            options={'managed': False},
        ),
    ]
